# Generated by Django 2.2.5 on 2020-10-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biodata',
        ),
    ]
