# Generated by Django 2.2.5 on 2020-10-06 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0003_biodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='biodata',
            old_name='picture',
            new_name='profile_pic',
        ),
        migrations.AddField(
            model_name='biodata',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='awards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='bus_decription',
            field=models.TextField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='biodata',
            name='bus_logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/Services/logo'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='bus_profile',
            field=models.ImageField(blank=True, null=True, upload_to='static/Services/profile'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='bus_title',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='biodata',
            name='business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog/cover_pictures'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='facebook_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='instagram_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='persuade',
            field=models.TextField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='biodata',
            name='pinrest_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='profile',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='biodata',
            name='total_clients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='twitter_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='works_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='yrs_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('degree_of_perfection', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_of_perfection', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=35)),
                ('title', models.CharField(max_length=35)),
                ('description', models.TextField(max_length=35)),
                ('image1', models.ImageField(upload_to='static/portfolio/images')),
                ('image2', models.ImageField(upload_to='static/portfolio/images')),
                ('image3', models.ImageField(upload_to='static/portfolio/images')),
                ('proj_url', models.URLField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.ProductCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
