# Generated by Django 2.2.5 on 2020-10-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20201006_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='bus_decription',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='persuade',
            field=models.TextField(default='', max_length=150),
        ),
    ]
