# Generated by Django 3.2.5 on 2022-01-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20220126_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='bus_decription',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='bus_title',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='lga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='persuade',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='phn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
