# Generated by Django 3.2.5 on 2022-01-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_alter_biodata_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='user',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='bus_decription',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='bus_logo',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='bus_profile',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='bus_title',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='business',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='mrt',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='persuade',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='total_clients',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='works_completed',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='yrs_exp',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
