# Generated by Django 3.2.5 on 2022-02-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_auto_20220130_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='other_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='surname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
