# Generated by Django 3.2.5 on 2022-02-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_auto_20220212_0712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
