# Generated by Django 3.2.5 on 2022-02-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_delete_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='ocupation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
