# Generated by Django 3.2.5 on 2022-02-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_biodata_ocupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='student_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
