# Generated by Django 3.2.5 on 2022-03-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_alter_biodata_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='instagram_page',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='ocupation',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='pinrest_page',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='twitter_page',
        ),
        migrations.AddField(
            model_name='biodata',
            name='_clas',
            field=models.PositiveIntegerField(choices=[('Choose', ''), (1, 'Jss1'), (2, 'Jss2'), (3, 'Jss3'), (4, 'Sss1'), (5, 'Sss2'), (6, 'Sss3'), (7, 'Graduate'), (8, 'Staff')], default=1),
        ),
    ]
