# Generated by Django 3.2.5 on 2022-03-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_auto_20220318_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='_clas',
            field=models.PositiveIntegerField(choices=[('Choose', ''), (1, 'Jss1'), (2, 'Jss2'), (3, 'Jss3'), (4, 'Sss1'), (5, 'Sss2'), (6, 'Sss3'), (7, 'Graduate'), (8, 'Staff')], default=1, verbose_name='class'),
        ),
    ]
