# Generated by Django 2.2.5 on 2020-10-06 11:21

import autoslug.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=datetime.datetime(2020, 10, 6, 11, 21, 56, 399005, tzinfo=utc), editable=False, populate_from='title', unique_with=('created__month',)),
            preserve_default=False,
        ),
    ]
