# Generated by Django 2.2.5 on 2020-10-06 11:22

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201006_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title', unique_with=('created__month',)),
            preserve_default=False,
        ),
    ]
