# Generated by Django 2.2.5 on 2020-10-06 11:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201006_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='updated__month', unique_with=('created__month',)),
        ),
    ]
