# Generated by Django 3.2.5 on 2022-01-26 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.session'),
            preserve_default=False,
        ),
    ]
