# Generated by Django 3.2.5 on 2022-01-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_term_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
