# Generated by Django 3.2.5 on 2022-01-26 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test', models.PositiveIntegerField(default=0)),
                ('second_test', models.PositiveIntegerField(default=0)),
                ('third_test', models.PositiveIntegerField(default=0)),
                ('examination', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.term')),
            ],
        ),
    ]
