# Generated by Django 3.2.5 on 2022-01-29 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0005_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='no_of_times_school_opened',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudenTermlytProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_from_the_teacher', models.TextField(blank=True, null=True)),
                ('comment_from_the_principal', models.TextField(blank=True, null=True)),
                ('promoted', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.term')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=7)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.term')),
            ],
        ),
    ]
