# Generated by Django 3.2.5 on 2022-01-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20220129_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(choices=[('Choose', ''), ('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], max_length=15),
        ),
    ]
