# Generated by Django 3.2.5 on 2022-01-29 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0007_alter_term_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Choose', ''), ('Jss1', 'Jss1'), ('Jss2', 'Jss2'), ('Jss3', 'Jss3'), ('Sss1', 'Sss1'), ('Sss3', 'Sss2'), ('Sss3', 'Sss3')], max_length=7)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.term')),
            ],
        ),
        migrations.RenameModel(
            old_name='StudenTermlytProfile',
            new_name='StudentTermlytProfile',
        ),
        migrations.RemoveField(
            model_name='score',
            name='session',
        ),
        migrations.RemoveField(
            model_name='score',
            name='term',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.AddField(
            model_name='score',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.level'),
            preserve_default=False,
        ),
    ]
