# Generated by Django 3.2.5 on 2022-01-29 10:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0008_auto_20220129_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentTermlytProfile',
            new_name='StudentTermlyProfile',
        ),
    ]
