# Generated by Django 3.2.5 on 2022-02-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_auto_20220211_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='clas',
            field=models.CharField(max_length=10),
        ),
    ]
