# Generated by Django 3.2.5 on 2022-02-12 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_delete_productcategory'),
        ('academy', '0014_alter_clas_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.biodata'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.biodata'),
        ),
        migrations.AlterField(
            model_name='studenttermlyprofile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.biodata'),
        ),
    ]
