# Generated by Django 3.2.5 on 2022-02-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_auto_20220212_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='clases',
            field=models.ManyToManyField(blank=True, null=True, to='academy.Subject'),
        ),
    ]
