# Generated by Django 3.2.5 on 2022-02-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_level_clases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='clases',
            new_name='subjects',
        ),
    ]
