# Generated by Django 3.2.5 on 2022-02-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_rename_clases_level_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='subjects',
        ),
        migrations.AddField(
            model_name='clas',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='academy.Subject'),
        ),
    ]
