# Generated by Django 3.2.5 on 2022-03-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_auto_20220219_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='examination',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='first_test',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='second_test',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='third_test',
            field=models.PositiveIntegerField(),
        ),
    ]
