# Generated by Django 3.2.5 on 2022-03-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_auto_20220317_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='examination',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='first_test',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='second_test',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='third_test',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
