# Generated by Django 3.2.5 on 2022-03-17 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_alter_biodata_student_id'),
        ('academy', '0020_auto_20220317_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttermlyprofile',
            name='term',
        ),
        migrations.AddField(
            model_name='studenttermlyprofile',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studenttermlyprofile',
            name='promoted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.clas')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.biodata')),
            ],
        ),
    ]
