# Generated by Django 3.2.5 on 2022-04-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_auto_20220317_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='clas',
            field=models.CharField(max_length=10, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='clas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.clas', verbose_name='class'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('level', 'student', 'subject'), name='Student cannot have a double record of the same subject at the same level'),
        ),
    ]
