# Generated by Django 3.2.5 on 2022-04-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0022_auto_20220405_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttermlyprofile',
            name='no_open',
            field=models.PositiveIntegerField(default=128),
        ),
        migrations.AddField(
            model_name='studenttermlyprofile',
            name='no_present',
            field=models.PositiveIntegerField(default=128),
        ),
    ]
